### ISSUE TITLE
Implementation with Java 17 document.getData() doesn't exist

### ISSUE THREAD

**Issue by Daftus** [hirannor/xml-digital-signature-java#1]
Hi,

I don't know if didn't set something correctly but I tried to add those classes to my Java 17 project and IntelliJ can't find the Document class in: 
`public byte[] generateDetachedSignature(final Document document, final String digestMethod, final String signatureMethod);`

My only import options are:

- `com.sun.xml.txw2`
- `org.w3c.dom`

I tried both to import in the XmlDigitalSignatureImpl class and XmlDigitalSignature interface and it resulted in that both `document.getData();` and `document.getFileName();` cannot be resolved.

Any idea or is it just me that is doing something wrong ?

Thanks

**Comment by hirannor** [comment]
Hi Clément Lmz,

I'm not quite sure, because I don't see your code. Anyway I don't really
know what are the changes between java 11 and java 17 regarding the digital
signatures.
I guess there is a "conflict" between the imports and my presumption is
that the Document as a class also exists in the java org.w3c.dom package.
Try to use full qualified name for the Document POJO, which also exist in
my repository.

Best regards,
Mate

**Comment by Daftus** [comment]
Thanks for the quick answer.

I was able to make it work by reloading all of my dependencies and deleting the org.w3c.dom that were unused.
I guess that solved the problem !

I'm closing it, thanks
